# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@devop.nyc
  admin_password: changeme
  domain_name: devop.nyc
  secret_key_base: 09ed15405cb13aee1f7729fede41a2c700abccf73964737244bc4914fbe8ce2ee82baa2a840a6e1c604a03e7ac3de08fd68cec50096f6ceedafb5e0c4d545eff

test:
  domain_name: devop.nyc 
  secret_key_base: b1043ada3ed319e15bfe6ca25b95840aba89d4c2fddc4d310e63afe18ffbae1a5800adae0820b2a5b8efc7c9ad657f2bdfdce195576c8c9f5ef1164f0b0d3c35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
